-- Tarea 1 - Ingenieria de Software 1
-- Marcos Campos 10-10108
-- Andrea Salcedo 10-10666
-- Seccion 1

DROP TABLE TIENE;
DROP TABLE POSEE;
DROP TABLE PAGA;
DROP TABLE ESTA_AFILIADO;
DROP TABLE ES_DUENIO;
DROP TABLE CONTIENE;
DROP TABLE COMENTARIO;
DROP TABLE FACTURA;
DROP TABLE TELEFONO;
DROP TABLE TARJETA;
DROP TABLE EFECTIVO;
DROP TABLE CONSUME;
DROP TABLE ADICIONAL;
DROP TABLE SERVICIO;
DROP TABLE PRODUCTO;
DROP TABLE PLAN;
DROP TABLE PAQUETE;
DROP TABLE FORMA_PAGO;
DROP TABLE CLIENTE;